{% set name = "mcap-owa-support" %}
{% set version = "0.5.1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mcap_owa_support-{{ version }}.tar.gz
  sha256: 50d795d0a028fc4ac07f018064ca4c6f4467313730a9cc1be385b2405f8ee0d8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - owa-core
    - easydict >=1.13
    - orjson >=3.10.15
    - mcap >=1.2.2
    - requests >=2.32.3
    - packaging >=25.0

test:
  imports:
    - mcap_owa
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/open-world-agents/open-world-agents
  summary: OWA support for the Python MCAP library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MilkClouds
